### ISSUE TITLE
Compilation Error in SharpEdge.cs

### ISSUE THREAD

**Issue by cbrnrd** [djhohnstein/SharpWeb#1]
I've attempted to build this using MSBuild.exe as well as Visual Studio, and they both come up with the same compile-time error:

```
1>------ Build started: Project: SharpWeb, Configuration: Debug Any CPU ------
1>C:\Users\Carter\Source\Repos\SharpWeb\Edge\SharpEdge.cs(134,40,134,63): error CS1528: Expected ; or = (cannot specify constructor arguments in declaration)
1>C:\Users\Carter\Source\Repos\SharpWeb\Edge\SharpEdge.cs(134,40,134,41): error CS1003: Syntax error, '[' expected
1>C:\Users\Carter\Source\Repos\SharpWeb\Edge\SharpEdge.cs(134,48,134,63): error CS1026: ) expected
1>C:\Users\Carter\Source\Repos\SharpWeb\Edge\SharpEdge.cs(134,48,134,63): error CS1003: Syntax error, ',' expected
1>C:\Users\Carter\Source\Repos\SharpWeb\Edge\SharpEdge.cs(134,63,134,64): error CS1003: Syntax error, ']' expected
1>C:\Users\Carter\Source\Repos\SharpWeb\Edge\SharpEdge.cs(134,63,134,64): error CS1002: ; expected
1>C:\Users\Carter\Source\Repos\SharpWeb\Edge\SharpEdge.cs(134,63,134,64): error CS1513: } expected
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========
```

#### .NET Version: 4.6.2

**Comment by djhohnstein** [comment]
A quick pass at this shows me it still compiles on 4.6.2 via Visual Studio Community 2017. It's possible I have an unstaged commit somewhere locally that's causing problems. I'll try it in a fresh VM in the morning and report back with my results; thanks for the report!

**Comment by djhohnstein** [comment]
Tested again on a Windows 10 x64-bit virtual machine, installed Visual Studio Community 2017 and downloaded a zip of the repo. Compiled for 4.6.1, and after I installed 4.6.2, successfully compiled. If you'd like, I can create a releases tab and release binaries for .NET 2.0, 3.5 and 4.6.

If the environment I listed above doesn't seem accurate to yours, let me know what information I'm missing. Otherwise I'll close the issue out in a day or so.

**Comment by cbrnrd** [comment]
That's odd. I guess the only difference is our visual studio versions. I'll
install 2017 > 2015 and see if anything changes.

**Comment by cbrnrd** [comment]
A releases tag would probably be great!

**Comment by djhohnstein** [comment]
Compiled the binaries quickly for 2.0, 3.5 and 4.6 CLR here: https://github.com/djhohnstein/SharpWeb/releases

If _those_ don't work feel free to open another issue.

**Comment by cbrnrd** [comment]
Works like a charm, thanks!
